server:
  port: 8081
broker:
  metric:
    topic: v1.metric.topic
    groupId: metricsconsumer
    partitions: 1
    replication: 1
spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USERNAME}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?reWriteBatchedInserts=true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
